services:
  app:
    container_name: unificando-frontend
    build:
      context: .
      args:
        VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
        VITE_N8N_WEBHOOK_URL: ${VITE_N8N_WEBHOOK_URL}
        VITE_CHATWOOT_TOKEN: ${VITE_CHATWOOT_TOKEN}
    ports:
      - "127.0.0.1:11004:80"
    restart: always
    environment:
      - NGINX_ENTRYPOINT_LOCAL_RESOLVERS=0
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
    cap_drop:
      - ALL
