export const ROUTES = {
  HOME: "/",
  SOLUTIONS: "/solucoes",
  CUSTOMER_SERVICE: "/solucoes/atendimento-whatsapp-instagram",
  PRODUCTIVITY: "/solucoes/inteligencia-artificial-negocios",
  DIGITAL_PRESENCE: "/solucoes/criacao-sites-profissionais",
  HOW_IT_WORKS: "/metodo-unificando",
  PLANS: "/planos",
  ABOUT: "/sobre",
  CONTACT: "/contato",
  CONTRACT: "/contrato",
  PRIVACY: "/privacidade",
  TERMS: "/termos",
  NOT_FOUND: "/404",
} as const;
