export const ROUTES = {
  HOME: "/",
  SERVICES: "/servicos",
  CUSTOMER_SERVICE: "/servicos/atendimento",
  PRODUCTIVITY: "/servicos/ia",
  DIGITAL_PRESENCE: "/servicos/sites",
  HOW_IT_WORKS: "/metodo-unificando",
  PLANS: "/planos",
  ABOUT: "/sobre",
  CONTACT: "/contato",
  CONTRACT: "/contrato",
  PRIVACY: "/privacidade",
  TERMS: "/termos",
  LINKS: "/links",
  NOT_FOUND: "/404",
  FOR_LAWYERS: "/para-advogados",
  SMART_HOSTING: "/servicos/hospedagem-inteligente",
} as const;
